name: Actualizar inflación esperada

on:
  schedule:
    # Primer día de cada mes a las 00:30 UTC
    - cron: '30 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar actualización
        run: python update_inflacion_esperada.py

      - name: Commit y push cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add indices/inflacion_esperada.json
          git diff --quiet --cached || git commit -m "Actualiza Inflación REM próxima fecha"
          git push
