name: Actualizar inflaci贸n esperada

# Dale permiso de escritura al GITHUB_TOKEN
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          # Asegura que el token persista y pueda usar permisos
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Ejecutar script de actualizaci贸n
        run: python update_inflacion_esperada.py

      - name: Commit y push cambios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add indices/inflacion_esperada.json
          git diff --quiet --cached || git commit -m "Actualiza Inflaci贸n REM pr贸xima fecha"
          git push
