name: 🔄 Actualizar cer.json

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'  # todos los días a las 10:00 UTC

jobs:
  update_cer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar update_cer.py
        run: python update_cer.py

      - name: Commit & Push cer.json si cambió
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add indices/cer.json
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Actualiza cer.json"
            git push
          fi
