name: 🏦 Actualizar activa.json

permissions:
  contents: write     # para que GITHUB_TOKEN pueda commitear

on:
  workflow_dispatch: {}    # habilita corrida manual
  schedule:
    - cron: '0 9 * * *'    # todos los días a las 09:00 UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar script
        run: python update_activa.py

      - name: Commit & Push si hay cambios
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add indices/activa.json
          # sólo commitea si hay diferencias
         git diff --cached --quiet \
           || (git commit -m "🔄 Actualiza indices/activa.json" && git push)
