name: 🔄 Actualizar inflacion.json

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update_inflacion:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 python-dateutil

      - name: Ejecutar update_inflacion.py
        run: python update_inflacion.py

      - name: Commit & Push inflacion.json si cambió
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add indices/inflacion.json
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Actualiza inflacion.json"
            git push
          fi
