name: Update SMVM

# 1) Aseguramos permisos de escritura sobre el contenido
permissions:
  contents: write

on:
  schedule:
    - cron: '0 18 1 * *'    # el día 1 de cada mes a las 18:00 UTC
  workflow_dispatch:       # o manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout con credenciales
        uses: actions/checkout@v3
        with:
          # forzamos a usar el GITHUB_TOKEN con permisos de escritura
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests beautifulsoup4

      - name: Ejecutar update_smvm.py
        run: python update_smvm.py

      - name: Commit & Push smvm.json si cambió
        run: |
          if [[ `git status --porcelain` ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add indices/smvm.json
            git commit -m "🔄 Actualiza SMVM al $(date +'%b-%y')"
            git push
          else
            echo "No hay cambios en smvm.json"
          fi
