name: 🔄 Actualizar ripte.json

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Ejecutar update_ripte.py
        run: python update_ripte.py

      - name: Commit & Push ripte.json si cambió
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add indices/ripte.json
          if ! git diff --cached --quiet; then
            git commit -m "🔄 Actualiza ripte.json"
            git push
          fi
