# .github/workflows/update_cer.yml
name: Actualizar CER

# ⚠️ Necesario para dar permiso de push al token de Actions
permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  actualizar-cer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          # explicitá el token y permití persistir credenciales
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Configurar Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sincronizar con main (pull/rebase)
        run: git pull origin main --rebase

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4 urllib3

      - name: Ejecutar update_cer.py
        run: python update_cer.py

      - name: Commit & Push cer.json si cambió
        run: |
          git add indices/cer.json
          if git diff --cached --quiet; then
            echo "✅ No hay cambios en cer.json"
          else
            git commit -m "Actualiza cer.json"
            git push origin main
          fi
